name: tajiryol_collector
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  cupertino_icons: ^1.0.0

  # state and network
  get: ^4.0.0-nullsafety.2
  provider: ^5.0.0
  dio: ^3.0.10 #dio: ^4.0.0-prev3
  json_annotation: ^3.1.1

  #UI
  # pull_to_refresh: ^1.6.4
  # flutter_screenutil: ^5.0.0-nullsafety.11
  # modal_bottom_sheet: ^2.0.0
  # dropdown_search: ^0.5.0
  # barcode: ^2.1.0
  barcode_widget: ^2.0.1
  flutter_barcode_scanner: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.0 #nnbd - ^0.20.0-nullsafety.3
  shared_preferences: ^2.0.5 #^2.0.3
  cached_network_image: ^2.5.1 #cached_network_image: ^3.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^3.5.1 #json_serializable: ^4.1.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
  